### ISSUE TITLE
swww-daemon crashes after systemd suspend

### ISSUE THREAD

**Issue by xk67** [LGFae/swww#270]
## Description
Crashes intermittently after at least 1 to 2 hours of system suspend.
I always have a second monitor connected via HDMI during this time.

## System Info
swww: 0.9.1
Hyprland: built from branch  at commit v0.37.1
nixos: 24.05pre608655.ff0dbd94265a (Uakari)

## Log
09:07:36 [INFO] (main) Initialization succeeded! Starting main loop...
09:07:36 [INFO] (main) Selected wl_shm format: Bgr888
09:07:36 [INFO] (transition) BumpPool with: 2 buffers. Size: 12150Kb
Io error: Broken pipe (os error 32)
thread 'main' panicked at daemon/src/main.rs:175:35:
failed to read the event queue: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
09:24:39 [INFO] (main) Removed socket at "/run/user/1000/swww.socket"
09:24:48 [INFO] (main) Initialization succeeded! Starting main loop...
09:24:48 [INFO] (main) Selected wl_shm format: Bgr888
09:24:48 [INFO] (transition) BumpPool with: 2 buffers. Size: 12150Kb
11:42:01 [INFO] (main) Goodbye!
12:52:15 [INFO] (main) Initialization succeeded! Starting main loop...
12:52:15 [INFO] (main) Selected wl_shm format: Bgr888
12:52:15 [INFO] (transition) BumpPool with: 2 buffers. Size: 12150Kb
thread 'main' panicked at /build/swww-0.9.1-vendor.tar.gz/smithay-client-toolkit/src/output.rs:575:14:
Received event for dead output
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
17:21:51 [INFO] (main) Removed socket at "/run/user/1000/swww.socket"

**Comment by nergdron** [comment]
I'm getting this on `hyprland 0.42.0` as well, `swww 0.9.5-2`, `linux 6.6.44-3-lts`, on Arch.

**Comment by Shoxx98** [comment]
maybe this is related: I am on sway 1.10 and after 15 min of continuous functionality I get this error: 
```
swww-daemon
         0ms [INFO]  Selected wl_shm format: Bgr
        63ms [INFO]  BumpPool with: 1 buffers. Size: 6075Kb
        73ms [INFO]  BumpPool with: 1 buffers. Size: 6075Kb
       531ms [INFO]  BumpPool with: 1 buffers. Size: 24300Kb
       561ms [INFO]  BumpPool with: 2 buffers. Size: 12150Kb
     31223ms [INFO]  BumpPool with: 3 buffers. Size: 18225Kb
 thread 'main' panicked at daemon/src/wallpaper.rs:415:70:
called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    846228ms [ERROR] error destroying wp_viewport: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846228ms [ERROR] error destroying wp_fractional_scale_v1: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846228ms [ERROR] error destroying zwlr_layer_surface_v1: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846228ms [ERROR] failed to destroy wl_buffer: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846228ms [ERROR] failed to destroy wl_shm_pool: Broken pipe (os error 32)
    846235ms [ERROR] error destroying wp_viewport: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846235ms [ERROR] error destroying wp_fractional_scale_v1: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846235ms [ERROR] error destroying zwlr_layer_surface_v1: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846235ms [ERROR] failed to destroy wl_buffer: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846235ms [ERROR] failed to destroy wl_buffer: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846235ms [ERROR] failed to destroy wl_buffer: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846235ms [ERROR] failed to destroy wl_shm_pool: Broken pipe (os error 32)
    846246ms [ERROR] error destroying wp_viewport: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846246ms [ERROR] error destroying wp_fractional_scale_v1: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846246ms [ERROR] error destroying zwlr_layer_surface_v1: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846246ms [ERROR] failed to destroy wl_buffer: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
    846246ms [ERROR] failed to destroy wl_shm_pool: Broken pipe (os error 32)
    846346ms [INFO]  Removed socket at /run/user/1000/swww-wayland-1.sock
```

**Comment by TotalTaxAmount** [comment]
I have the same issue aswell
