### ISSUE TITLE
swww-daemon crash on utf8 error

### ISSUE THREAD

**Issue by mamaraddio** [LGFae/swww#304]
Hi @LGFae,

I'm opening this issue to report that using the git AUR package when I issue a `swww img path/to/image --filter CatmullRom` command the daemon crashes.

Also I have transition type (any), transition step (90) and duration (2) configured through env variables and with the -git version the transition seems to not be applied, is like the image is unloaded a millisecond of black screen and then the new image

The same does not happen with the release version of the swww package (v0.9.5)

If you need some output to identify the issue let me know what I have to run

<details><summary>My system</summary>
<p>

OS: Arch Linux x86_64
Kernel: 6.8.9-arch1-1
WM: Hyprland (Wayland)
CPU: Intel(R) Core(TM) i7-9750HF (12) @ 4,50 GHz
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q [Discrete]

</p>
</details>

**Comment by muni-corn** [comment]
potentially related crash when i go to change wallpapers:

```console
~ 
❯ swww-daemon
       3ms [INFO]  (main) Selected wl_shm format: Bgr888
       4ms [INFO]  (main) Initialization succeeded! Starting main loop...
       6ms [WARN]  (main) Received transform. We currently ignore those
       6ms [WARN]  (main) Received transform. We currently ignore those
       6ms [WARN]  (main) Received transform. We currently ignore those
      95ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 6075Kb
      98ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 6075Kb
     111ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 10800Kb
thread 'main' panicked at utils/src/ipc.rs:1160:10:
received a non utf8 string from socket: Utf8Error { valid_up_to: 86, error_len: Some(1) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    3354ms [INFO]  (main) Removed socket at "/run/user/1001/swww-wayland-1.socket"

~ took 3s 
• 101 ❯ swww-daemon --version
swww-daemon 0.9.5-master
```

**Comment by mamaraddio** [comment]
Yeah also I got the same output

**Comment by LGFae** [comment]
I think I know how to fix it, but I currently have no access to electricity. I don't know when it will come back (and when it does, I'll have more pressing problems to attend to), so it might a long time

**Comment by muni-corn** [comment]
@LGFae If you'd like to try and explain the fix, I can attempt to fix it for you :grin:

**Comment by LGFae** [comment]
I was explaining my thoughts, but then I realized I am probably wrong. You'd have to try printing out the values we are serializing and deserializing in utils/src/ipc to try and figure out what's wrong.

**Comment by LGFae** [comment]
Good new: the lights are back! Bad news: I can't reproduce this.

Can you guys try a couple of things for me? See if this still happens if you run the daemon with `--format xrgb`. If it does, run the daemon with `RUST_BACKTRACE=1` and post the backtrace you are getting when the error happens.

**Comment by mamaraddio** [comment]
Running it with `--format xrgb` gave me the same issue, monitor setup is integrated laptop monitor (1080p) + 1 HDMI (1440p) monitor, no scaling

Interestingly just today I made a system upgrade (`pacman -Su`) and my system upgraded a lot of packages, including `linux` and `nvidia` and relateed. Now with **swww-daemon 0.9.5-master** the issue has gone, so neither do I can reproduce it right now.

@muni-corn you are still able to reproduce it?

**Comment by abs3ntdev** [comment]
this is still happening for me. I am not seeing anything useful in the print even with RUST_BACKTRACE

```
RUST_BACKTRACE=1 swww-daemon --format xrgb
       0ms [INFO]  (main) Forced usage of wl_shm format: Xrgb8888
       6ms [INFO]  (main) Initialization succeeded! Starting main loop...
       8ms [WARN]  (main) Received transform. We currently ignore those
       8ms [WARN]  (main) Received transform. We currently ignore those
     318ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 14400Kb
     328ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 14400Kb
thread 'main' panicked at utils/src/ipc.rs:1160:10:
received a non utf8 string from socket: Utf8Error { valid_up_to: 56, error_len: Some(1) }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    5408ms [INFO]  (main) Removed socket at "/run/user/1000/swww-wayland-1.socket"```
 ```
    
I also noticed that if I specify a single monitor to the --outputs flag then it doesn't crash. it only crashes when I don't provide --outputs at all or if i specify --outputs=DP-1,DP-2
    
  my monitor setup:
  
  ```
  Monitor DP-1 (ID 0):
	2560x1440@164.99899 at 2560x0
	description: ASUSTek COMPUTER INC VG27A L4LMQS004814
	make: ASUSTek COMPUTER INC
	model: VG27A
	serial: L4LMQS004814
	active workspace: 6 (6)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 3
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@59.95Hz 2560x1440@165.00Hz 2560x1440@160.00Hz 2560x1440@155.00Hz 2560x1440@143.97Hz 2560x1440@120.00Hz 1920x1080@119.88Hz 1920x1080@100.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1152x864@75.00Hz 1440x576@50.00Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz

Monitor DP-2 (ID 1):
	2560x1440@164.99899 at 0x560
	description: ASUSTek COMPUTER INC VG27A L4LMQS004783
	make: ASUSTek COMPUTER INC
	model: VG27A
	serial: L4LMQS004783
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 0 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 2560x1440@59.95Hz 2560x1440@165.00Hz 2560x1440@160.00Hz 2560x1440@155.00Hz 2560x1440@143.97Hz 2560x1440@120.00Hz 1920x1080@119.88Hz 1920x1080@100.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1280x1024@75.03Hz 1280x1024@60.02Hz 1440x900@59.89Hz 1152x864@75.00Hz 1440x576@50.00Hz 1024x768@75.03Hz 1024x768@70.07Hz 1024x768@60.00Hz 800x600@75.00Hz 800x600@72.19Hz 800x600@60.32Hz 800x600@56.25Hz 640x480@75.00Hz 640x480@72.81Hz 640x480@59.94Hz
```

**Comment by LGFae** [comment]
Ah, yes. To get a proper backtrace, you'd have to run the debug version. I should have mentioned that. 

I tried forcing the latest master to crash, but failed to do so. I might have to test on a dual monitor setup myself. Might take a little bit.

By the way, does it also crash if you try calling `swww query`?

**Comment by abs3ntdev** [comment]
swww query does not crash 

```
swww query 
DP-1: 1440x2560, scale: 1, currently displaying: image: /home/abs3nt/Pictures/Wallpapers/wallhaven-d6eqmj.png
DP-2: 2560x1440, scale: 1, currently displaying: image: /home/abs3nt/Pictures/Wallpapers/wallhaven-d6eqmj.png
```

how do i run the debug version?

**Comment by abs3ntdev** [comment]
jk figured it out. here is logs from debug 

```
       0ms [DEBUG] (main) Made socket in "/run/user/1000/swww-wayland-1.socket" and initialized logger. Starting daemon...
       1ms [INFO]  (main) Selected wl_shm format: Bgr888
       1ms [DEBUG] (main) New output: wl_output@8
       1ms [DEBUG] (main) New output: wl_output@16
       1ms [INFO]  (main) Initialization succeeded! Starting main loop...
       9ms [DEBUG] (main) output wl_output@8 position: 0,0
       9ms [DEBUG] (main) Output wl_output@8 name: DP-1
       9ms [DEBUG] (main) Output wl_output@8 description: ASUSTek COMPUTER INC VG27A L4LMQS004814 (DP-1)
       9ms [WARN]  (main) Received transform. We currently ignore those
       9ms [DEBUG] (main) output wl_output@16 position: 0,0
       9ms [DEBUG] (main) Output wl_output@16 name: DP-2
       9ms [DEBUG] (main) Output wl_output@16 description: ASUSTek COMPUTER INC VG27A L4LMQS004783 (DP-2)
       9ms [WARN]  (main) Received transform. We currently ignore those
     135ms [DEBUG] (transition) output Some("DP-1") - drawing: image: /home/abs3nt/Pictures/Wallpapers/wallhaven-rrpwj1.png
     135ms [DEBUG] (transition) Starting transitions
     135ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 10800Kb
     140ms [DEBUG] (transition) output Some("DP-2") - drawing: image: /home/abs3nt/Pictures/Wallpapers/wallhaven-rrpwj1.png
     140ms [DEBUG] (transition) Starting transitions
     140ms [INFO]  (transition) BumpPool with: 1 buffers. Size: 10800Kb
     143ms [DEBUG] (transition) Transitions finished
     147ms [DEBUG] (transition) Transitions finished
     158ms [DEBUG] (main) Output wl_output@8: Surface Enter
     180ms [DEBUG] (main) Output wl_output@16: Surface Enter
thread 'main' panicked at utils/src/ipc.rs:1160:10:
received a non utf8 string from socket: Utf8Error { valid_up_to: 55, error_len: Some(1) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1034:23
   4: utils::ipc::deserialize_string
             at /home/abs3nt/repos/github.com/LGFae/swww/utils/src/ipc.rs:1159:5
   5: utils::ipc::Request::receive
             at /home/abs3nt/repos/github.com/LGFae/swww/utils/src/ipc.rs:701:32
   6: swww_daemon::Daemon::recv_socket_msg
             at /home/abs3nt/repos/github.com/LGFae/swww/daemon/src/main.rs:372:23
   7: swww_daemon::main
             at /home/abs3nt/repos/github.com/LGFae/swww/daemon/src/main.rs:203:31
   8: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    5215ms [INFO]  (main) Removed socket at "/run/user/1000/swww-wayland-1.socket"
```

**Comment by LGFae** [comment]
I think commit e4797395f656336a328ec4fcb3bbb2e35457d67c fixes it. Can you check the latest master again?

**Comment by abs3ntdev** [comment]
seems to be working again

**Comment by LGFae** [comment]
Thanks a lot for your help!

**Comment by muni-corn** [comment]
awesome, thanks for getting this fixed! <3
